### ISSUE TITLE
dropdown position not aligned to the text field

### ISSUE THREAD

**Issue by fklm0001** [insideApple/VPAutoComplete#2]
Hi, good day! How can I align the dropdown list below to the text field? 
Here's my text field:
![image](https://user-images.githubusercontent.com/8587191/38976750-c6609e50-43e4-11e8-811c-fca7fb6baeaa.png)

Then it overlaps the field when the dropdown is shown.
![image](https://user-images.githubusercontent.com/8587191/38976728-b5ff81ca-43e4-11e8-9444-f3f4dff7dd20.png)

Help me please!! Thanks in advance!

**Comment by insideApple** [comment]
Are you using dropdown in tableview?

**Comment by fklm0001** [comment]
Hi sir! Thanks for replying. No sir, I'm just using it in the UIView then Scroll View.

**Comment by insideApple** [comment]
Can you post your code?

**Comment by fklm0001** [comment]
For a while sir...

**Comment by insideApple** [comment]
I think you are setting onView to Main view like.
dropDown.onView = self.view

If your textfield is in ScrollView you should set
dropDown.onView = yourScrollView

**Comment by fklm0001** [comment]
Oh I see. Let me test it sir... Sorry. :) I'm just a newbie in iOS Swift development... :D Btw, here's my code.

![image](https://user-images.githubusercontent.com/8587191/38981432-0091144e-43f2-11e8-8e0f-2b4e01836003.png)

**Comment by insideApple** [comment]
Ok try it and Let me know if you still have any issue?

**Comment by fklm0001** [comment]
Hi sir. It's now okay. Thanks a lot for this! T'was a big help!

![image](https://user-images.githubusercontent.com/8587191/38982004-4a9ce936-43f3-11e8-9f51-5f97f57eb8e0.png)

**Comment by insideApple** [comment]
Great I will sure add it in description so it can help others.
