### ISSUE TITLE
Last few items showing below keyboard sometimes

### ISSUE THREAD

**Issue by thundercatchris** [insideApple/VPAutoComplete#3]
Im using a tableView with IQKeyboardManagerSwift. Works great apart from on initial load and some other occasions where the table is behind the keyboard partly

Is there any way to always force the list to go above the textField? Ive tried isOnTop = true

<img width="286" alt="screen shot 2018-08-30 at 10 37 49" src="https://user-images.githubusercontent.com/28560438/44843810-1df13980-ac41-11e8-9871-ca8b09f4459f.png">

**Comment by insideApple** [comment]
This will be enhancement. i will add it as soon as possible.
Thank you

**Comment by insideApple** [comment]
Added `showAlwaysOnTop` flag to show dropdown always on top
